### ISSUE TITLE
Handle RPC return codes appropriately

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-transport-vsomeip-rust#20]
Currently we either return E_OK or MT_RESPONSE on SOME/IP side

i.e handle [this TODO](https://github.com/eclipse-uprotocol/up-transport-vsomeip-rust/blob/acbb0d0c9b8b48dd35c74f461e97151f1e922000/up-transport-vsomeip/src/message_conversions.rs#L253)

and [this](https://github.com/eclipse-uprotocol/up-transport-vsomeip-rust/blob/acbb0d0c9b8b48dd35c74f461e97151f1e922000/up-transport-vsomeip/src/message_conversions.rs#L507) correctly

EDIT: Adding the [spec link](https://github.com/eclipse-uprotocol/up-spec/blob/main/up-l1/someip.adoc#225-communication-status) for this mapping.

**Comment by dmacattack** [comment]
dibs

**Comment by PLeVasseur** [comment]
Done!

**Comment by PLeVasseur** [comment]
Hoikily dokily, assigned
